config/routes.rb
Rails.application.routes.draw do
  resources :schools

  resources :courses do
    get "enroll_self", to: "courses#enroll_self", as: "enroll_self"
  end
  resources :students
  
  get "login", to: "sessions#new", as: "login"
  post "login", to: "sessions#create", as: "create_session"
  get "logout", to: "sessions#destroy", as: "logout"


  root "courses#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord

  has_many :student_courses
  has_many :students, through: :student_courses 

  validates :name, presence: true, length: { maximum:50}
  validates :short_name, presence: true, length: { maximum:50}

  
end

app/models/school.rb
class School < ApplicationRecord
  validates :name, presence: true, length: {minimum:3, maximum:30}
end

app/models/student.rb
class Student < ApplicationRecord
  has_secure_password

  before_save { self.email = self.email.downcase}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: true
  validates :email, presence: true, length: { maximum: 105 },
                      uniqueness: { case_sensitive: false },
                      format: { with: VALID_EMAIL_REGEX }
  has_many :student_courses
  has_many :courses, through: :student_courses 
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :require_user
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= Student.find(session[:student_id]) if session[:student_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    cookies[:return_to_url] = request.url
    if !logged_in?
      flash[:notice] = "You must be logged in to view this page."
      redirect_to login_path
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  
  skip_before_action :require_user, only: [:index, :show]

  def index
    @courses = Course.all
  end

  def new
    
  end

  def create
    
  end

  def edit
    
  end

  def update
    
  end

  def destroy
    
  end
  
  def enroll_self
    course = Course.find params[:course_id]
    if course.in? current_user.courses
      flash[:warning] = "You can't enroll in a course that you are already enrolled!"
    else
      course.students << current_user 
      flash[:notice] = "Congratulations. You enrolled in #{course.name}."
    end
    redirect_to courses_path
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  skip_before_action :require_user
  
  def about
  end

end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: %i[ show edit update destroy ]

  # GET /schools or /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1 or /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools or /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to school_url(@school), notice: "School was successfully created." }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1 or /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to school_url(@school), notice: "School was successfully updated." }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1 or /schools/1.json
  def destroy
    @school.destroy

    respond_to do |format|
      format.html { redirect_to schools_url, notice: "School was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def school_params
      params.require(:school).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :require_user, only: [:new, :create]
  def new

  end

  def create
    @student = Student.find_by(email: params[:email].downcase)
    if @student and @student.authenticate(params[:password])
      flash[:notice] = "Welcome #{@student.name}. Please, explore all the things."
      session[:student_id] = @student.id
      redirect_to cookies[:return_to_url] || root_path
      cookies[:return_to_url] = nil
    else
      flash[:error] = "Something went wrong. Please, try again in a few moments."
      render :new
    end
  end

  def destroy
    session[:student_id] = nil
    flash[:notice] = "You have successfully logged out!"
    redirect_to login_path
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  skip_before_action :require_user, only: [:new, :create]
  before_action :set_student, only: [ :show, :edit, :update, :destroy]
  before_action :require_same_student, only: [:edit, :update]

  def index
    @students = Student.all
    flash.now[:notice] = helpers.pluralize(Student.all.count, "student") + " registered."
    respond_to do |format|
      format.html { }
    end
  end

  def show
  end

  def new
    @student = Student.new
    @student.name = Faker::Name.name
    @student.email = Faker::Internet.email
  end

  def create
    @student = Student.new(student_params)
    @student.password = Faker::Internet.password if @student.password.nil?
    @student.creator_id = Student.first.id
    respond_to do |format|
      if @student.save
        flash[:notice] = "Welcome #{@student.name}! Feel free to Explore!"
        session[:student_id] = @student.id
        format.html { redirect_to root_path }
      else
        flash.now[:error] = @student.errors.full_messages.to_sentence
        format.html { render :new }
      end
    end
  end

  def edit
    @student == current_user
  end

  def update
    respond_to do |format|
      if @student.update(student_params)
        flash[:notice] = "Student Updated!"
        format.html { redirect_to student_path(@student) }
      else
        flash.now[:error] = @student.errors.full_messages.to_sentence
        format.html { render :edit }
      end
    end
  end

  def destroy
  end

private
  def student_params
    params.require(:student).permit(:name, :email, :password, :password_confirmation)
  end

  def set_student
    @student = Student.find params[:id]
  end

  def require_same_student
    if current_user != @student
      flash[:error] = "You don't have the rights to perform this action."
      redirect_to student_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def render_turbo_stream_flash_messages
    turbo_stream.replace "flash", partial: "layouts/flash"
  end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/_course.html.erb
<div class="col s6 m6">
  <div class="card blue-grey darken-1">
    <div class="card-content white-text">
      <span class="card-title"><%= course.name %> (<%= course.short_name %>)</span>
      <p><%= course.description %></p>
    </div>
    <div class="card-action">
    
      <% if logged_in? and course.in? current_user.courses %>
        <a href="#">Visit Course Page</a>
      <% else %>
        <%= link_to("Enroll on this Course", course_enroll_self_path(course)) %>
      <% end %>
    </div>
  </div>
</div>

app/views/courses/index.html.erb
<div class="row">
  <div class="s12">
    <h3 class="center-align">Course Listing</h3>
    <p>cookie<%= cookies[:return_to_url] %></p>
  </div>
</div>
<div class="row">
  <%= render @courses %>
</div>

app/views/courses/new.html.erb
<h1>nova página de cursos</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MaterializeRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="turbo-cache-control" content="no-cache">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "materialize" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render  "shared/header" %>
    <%= render "shared/flash" %>
    <main class="container">
      <%= yield %>
    </main>
    <%= render  "shared/footer" %>
  </body>
</html>

app/views/pages/_test.html.erb
<p>adsfbljhasdbfl</p>

app/views/pages/about.html.erb
<h1>adsfasdf</h1>
<%= turbo_frame_tag "opa" do %>
  <%= link_to "Criar um novo", opa_pages_path %>
  <p>conteudo</p>
<% end %>

<p>Conteúdo fora de Avout</p>
<%= render  "test" %>

app/views/schools/_form.html.erb
<%= form_with(model: school) do |form| %>
  <% if school.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
        <% school.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/schools/_school.html.erb
<div id="<%= dom_id school %>">
  <p>
    <strong>Name:</strong>
    <%= school.name %>
  </p>

</div>

app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render "form", school: @school %>

<br>

<div>
  <%= link_to "Show this school", @school %> |
  <%= link_to "Back to schools", schools_path %>
</div>

app/views/schools/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Schools</h1>

<div id="schools">
  <% @schools.each do |school| %>
    <%= render school %>
    <p>
      <%= link_to "Show this school", school %>
    </p>
  <% end %>
</div>

<%= link_to "New school", new_school_path %>

app/views/schools/new.html.erb
<h1>New school</h1>

<%= render "form", school: @school %>

<br>

<div>
  <%= link_to "Back to schools", schools_path %>
</div>

app/views/schools/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @school %>

<div>
  <%= link_to "Edit this school", edit_school_path(@school) %> |
  <%= link_to "Back to schools", schools_path %>

  <%= button_to "Destroy this school", @school, method: :delete %>
</div>

app/views/shared/_account_dropdown.html.erb
<% if logged_in? %>
  <%= tag.li do %>
    <%= link_to student_path(current_user) do %>
      <%= tag.i("person", class: "material-icons") %>
      <%= tag.span("My Account") %>
    <% end %>
  <% end %>
  <%= tag.li do %>
    <%= link_to logout_path do %>
      <%= tag.i("logout", class: "material-icons") %>
      <%= tag.span("logout") %>
    <% end %>
  <% end %>
<% else %>
  <%= tag.li do %>
    <%= link_to login_path do %>
      <%= tag.i("login", class: "material-icons") %>
      <%= tag.span "Login" %>
    <% end %>
  <% end %>
  <%= tag.li do %>
    <%= link_to new_student_path do %>
      <%= tag.i("person_add", class: "material-icons") %>
      <%= tag.span "Sign Up" %>
    <% end %>
  <% end %>  
<% end %>

app/views/shared/_flash.html.erb
<turbo-frame id="flash">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <div class="toast-container" data-controller="toast" hidden data-key="<%= key %>">
        <span class="toast-content" data-toast-target="content"><%= value %></span>
      </div>
    </div>
  <% end %>
</turbo-frame>

app/views/shared/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Tech University</h5>
        <p class="grey-text text-lighten-4">Nice Description for my UNI :)</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Visit</h5>
        <ul>
          <li><%= link_to "Home", root_path, class: "grey-text text-lighten-3" %></li>
          <li><%= link_to "New Course", new_course_path, class: "grey-text text-lighten-3" %></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2014 Copyright Text
    <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header >
  <nav>
    <div class="nav-wrapper container">
      <%= link_to root_path, class: "brand-logo" do %>
        LOGO
      <% end %>
      <a href="#" data-target="mobile-sidenav" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <%= render "shared/navbar" %>
    </div>
  </nav>
</header>

<%= render "shared/sidenav" %>

<!-- Dropdown Structure -->
<ul id='students_drop1' class='dropdown-content below-origin'>
  <%= render "shared/account_dropdown" %>
</ul>
<ul id='students_drop2' class='dropdown-content below-origin'>
  <%= render "shared/account_dropdown" %>
</ul>

app/views/shared/_nav_links.html.erb
<li><%= link_to  "Home", root_path %></li>

<% if logged_in? %>
  <li><%= link_to  "Students", students_path %></li>
<% end %>

app/views/shared/_navbar.html.erb
<ul id="nav-mobile" class="right right hide-on-med-and-down">
  <%= render "shared/nav_links" %>
  <li>
    <%= link_to "#!", class: "dropdown-trigger", data: { target: "students_drop2" } do %>
      <%= tag.span(logged_in? ? "Welcome #{current_user.name}" : "Account") %>
      <%= tag.i("account_circle", class: "material-icons right") %>
    <% end %>
  </li>
</ul>

app/views/shared/_sidenav.html.erb
<ul class="sidenav" id="mobile-sidenav">
  <%= render "shared/nav_links" %>
  <li>
    <a class="dropdown-trigger" href="#!" data-target="students_drop1">
      Account<i class="material-icons right">account_circle</i>
    </a>
  </li>
</ul>

app/views/students/_student.html.erb
<div class="col s6 m6">
  <div class="card blue-grey darken-1">
    <div class="card-content white-text">
      <span class="card-title">Name: <%= student.name %></span>
      <span>Email: <%= student.email %></span>
      <p>Course enrolments  </p>
    </div>
    <div class="card-action">
      <%= link_to "View Profile", student_path(student) %>
      <%= link_to "Edit Profile", edit_student_path(student) if student == current_user %>
    </div>
  </div>
</div>

app/views/students/edit.html.erb
<div class="card-panel">
  <h3 class="center-align">Edit</h3>
  <div class="container">
    <div class="row center">
      <div class="col s12 m12 l12">
       <%= render partial: "students/partials/form" %>
      </div>
    </div>
  </div>
</div>

app/views/students/index.html.erb
<div class="row">
  <div class="s12">
    <h3 class="center-align">Student Listing</h3>
  </div>
</div>
<div class="row">
  <%= render @students %>
</div>

app/views/students/new.html.erb
<div class="card-panel">
  <h3 class="center-align">Sign Up!</h3>
  <div class="container">
    <div class="row center">
      <div class="col s12 m12 l12">
       <%= render partial: "students/partials/form" %>
      </div>
    </div>
  </div>
</div>

app/views/students/partials/_form.html.erb
<div class="row">
  <%= form_for(@student, html: {class: "col s12", data: {turbo: :false}}) do |f| %>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :name, autofocus: true %>
        <%= f.label :name %>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= f.email_field :email %>
        <%= f.label :email %>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= f.password_field :password, placeholder: "Set your Password here." %>
        <%= f.label :password %>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= f.password_field :password_confirmation, placeholder: "Confirm your Password." %>
        <%= f.label :password_confirmation %>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= f.button type: :submit, class:"btn waves-effect waves-light right" %>
      </div>
    </div>
  <% end %>
</div>

app/views/students/show.html.erb
<div class="row">
  <div class="col s6 m6 center">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title">Name: <%= @student.name %></span>
        <span>Email: <%= @student.email %></span>
        <p>Course enrolments:</p>
        <% if @student.courses.any? %>
          <ul>
            <% @student.courses.each do |course| %>
              <li><%= course.short_name %></li>
            <% end %>
          </ul>
        <% else %>
          <span>None</span>
        <% end %>
      </div>
      <div class="card-action">
        <%= link_to "Edit this Profile", edit_student_path(@student) %>
      </div>
    </div>
  </div>
</div>

<%= render @student.courses %>

app/views/students/updade.html.erb
<h1>Students#updade</h1>
<p>Find me in app/views/students/updade.html.erb</p>